### PR TITLE
Add unsignedInt valueType

### PR DESCRIPTION
**Pull request by mmarseu**
The unsignedInt type was missing from the valueType drop down box.

### CODE REVIEW

**Review by BirgitBoss — CHANGES_REQUESTED** [review]
Besides unsignedInt also unsignedInteger is missing

**Comment by mmarseu** [comment]
> Besides unsignedInt also unsignedInteger is missing

I can't find the type unsignedInteger in XML Schema 1.1. Is it defined somewhere else?

**Comment by BirgitBoss** [comment]
> > Besides unsignedInt also unsignedInteger is missing
> 
> I can't find the type unsignedInteger in XML Schema 1.1. Is it defined somewhere else?

You are right, sorry. I need to fix this is the current version of the spec. (not yet released).

**Comment by mmarseu** [comment]
@BirgitBoss No problem. Would you then approve this change?

**Comment by BirgitBoss** [comment]
> @BirgitBoss No problem. Would you then approve this change?

Yes

**Comment by mmarseu** [comment]
> > @BirgitBoss No problem. Would you then approve this change?
> 
> Yes

Would you also let Github know that? 😄 The PR is still marked as "Changes requested". 

And once you've approved, a maintainer must trigger the standard CI workflows. As a first time contributor, I can't do it myself.

**Review by BirgitBoss — APPROVED** [review]

**Pull request merged**
